// SPDX-License-Identifier: MIT
pragma solidity 0.8.23;

import {Initializable} from "@openzeppelin/contracts-upgradeable/proxy/utils/Initializable.sol";
import {UUPSUpgradeable} from "@openzeppelin/contracts-upgradeable/proxy/utils/UUPSUpgradeable.sol";
import {OwnableUpgradeable} from "@openzeppelin/contracts-upgradeable/access/OwnableUpgradeable.sol";
import {ECDSA} from "@openzeppelin/contracts/utils/cryptography/ECDSA.sol";

/**
 * @title NotaryAttestationVerifier
 * @notice UUPS-upgradeable. Two-layer TLSNotary → Ethereum bridge:
 *
 *   Layer 1 (off-chain):  Real TLSNotary MPC proof generated by the prover service,
 *                         notary's ed25519 signature verified off-chain by the oracle.
 *   Layer 2 (on-chain):   Oracle signs keccak256("DCT_TLSN", proofHash, endpointHash)
 *                         with its secp256k1 key → stored here for permissionless audit.
 *
 * Consumers (DCTEnforcer.validateActionWithScope) call verify() for pass/fail.
 * Anyone can call verifyAndCommit() to store a proof commitment on-chain.
 *
 * Proof format produced by server/lib/tlsn/:
 *   { url, method, statusCode, responsePreview, sessionHash, notarySignatureHex, proofHash }
 */
contract NotaryAttestationVerifier is Initializable, OwnableUpgradeable, UUPSUpgradeable {
    using ECDSA for bytes32;

    /// @notice Secp256k1 oracle key that bridges TLSNotary ed25519 proofs to Ethereum.
    address public notarySigner;

    /// @notice proofCommitments[proofHash] = block number when proof was committed.
    ///         proofHash = keccak256(tlsn proof JSON bytes) — set by verifyAndCommit().
    ///         Allows permissionless audit: anyone can hash the proof and check this mapping.
    mapping(bytes32 => uint256) public proofCommitments;

    event TlsnProofCommitted(
        bytes32 indexed proofHash,
        bytes32 indexed endpointHash,
        address indexed signer,
        uint256 blockNumber
    );
    event NotarySignerUpdated(address indexed oldSigner, address indexed newSigner);

    constructor() {
        _disableInitializers();
    }

    function initialize(address _notarySigner, address initialOwner) external initializer {
        __Ownable_init(initialOwner);
        __UUPSUpgradeable_init();
        require(_notarySigner != address(0), "DCT: zero notary");
        notarySigner = _notarySigner;
    }

    function _authorizeUpgrade(address newImplementation) internal override onlyOwner {}

    /**
     * @notice Update the oracle signer key (e.g. after key rotation).
     */
    function setNotarySigner(address _newSigner) external onlyOwner {
        require(_newSigner != address(0), "DCT: zero notary");
        emit NotarySignerUpdated(notarySigner, _newSigner);
        notarySigner = _newSigner;
    }

    /**
     * @notice Verify oracle attestation for DCTEnforcer.
     *
     * digest = keccak256(abi.encodePacked("DCT_TLSN", expectedEndpointHash))
     * This is the fast path used inline by validateActionWithScope.
     *
     * @param attestation 65-byte ECDSA signature from oracle
     * @param expectedEndpointHash keccak256(tool name bytes) — the tool/URL being proved
     */
    function verify(bytes calldata attestation, bytes32 expectedEndpointHash)
        external
        view
        returns (bool)
    {
        if (attestation.length != 65) return false;
        bytes32 digest = keccak256(abi.encodePacked("DCT_TLSN", expectedEndpointHash));
        address recovered = digest.recover(attestation);
        return recovered == notarySigner;
    }

    /**
     * @notice Verify AND commit a TLSNotary proof to storage.
     *
     * Called by anyone (agent, relayer, oracle) after a real TLSNotary proof is generated.
     * Stores proofHash → blockNumber so the proof can be audited permissionlessly.
     *
     * attestation covers BOTH proofHash and endpointHash so the oracle cannot mix commitments.
     * digest = keccak256(abi.encodePacked("DCT_TLSN_COMMIT", proofHash, endpointHash))
     *
     * @param proofHash   keccak256 of the raw TLSNotary proof JSON bytes
     * @param endpointHash keccak256(tool / URL bytes) — must match what DCTEnforcer checks
     * @param attestation  65-byte oracle ECDSA sig
     */
    function verifyAndCommit(
        bytes32 proofHash,
        bytes32 endpointHash,
        bytes calldata attestation
    ) external returns (bool) {
        require(attestation.length == 65, "DCT: attestation must be 65 bytes");
        bytes32 digest = keccak256(
            abi.encodePacked("DCT_TLSN_COMMIT", proofHash, endpointHash)
        );
        address recovered = digest.recover(attestation);
        require(recovered == notarySigner, "DCT: invalid oracle signature");

        proofCommitments[proofHash] = block.number;
        emit TlsnProofCommitted(proofHash, endpointHash, recovered, block.number);
        return true;
    }

    /**
     * @notice Check whether a proof has been committed on-chain.
     * @param proofHash keccak256 of the TLSNotary proof JSON
     */
    function isProofCommitted(bytes32 proofHash) external view returns (bool committed, uint256 atBlock) {
        atBlock = proofCommitments[proofHash];
        committed = atBlock > 0;
    }

    uint256[48] private __gap;
}
